"""
Usage Example 4: Scheduled Reporting
Demonstrates automated report generation and scheduling
"""

import asyncio
import logging
import sys
import os
from datetime import time

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from core.reporting import ReportScheduler, ReportConfig

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


async def main():
    """Example 4: Scheduled reporting"""
    
    print("=" * 70)
    print("USAGE EXAMPLE 4: Scheduled Reporting")
    print("=" * 70)
    print()
    print("This example sets up automated report generation:")
    print("  ✓ Daily executive summary")
    print("  ✓ Weekly PCI-DSS compliance report")
    print("  ✓ Monthly threat intelligence briefing")
    print()
    print("Reports generated by the Report Generation Agent")
    print()
    print("-" * 70)
    
    try:
        scheduler = ReportScheduler()
        
        # Schedule daily executive report
        logger.info("Configuring daily executive summary...")
        daily_report = ReportConfig(
            name='daily_executive_summary',
            report_type='executive',
            frequency='daily',
            time=time(8, 0),  # 8:00 AM
            recipients=['ciso@example.com', 'soc@example.com'],
            format='pdf',
            include_charts=True,
            include_recommendations=True
        )
        scheduler.add_report(daily_report)
        logger.info("  ✓ Daily executive report scheduled for 08:00")
        
        # Schedule weekly compliance report
        logger.info("Configuring weekly PCI-DSS compliance report...")
        weekly_report = ReportConfig(
            name='weekly_pci_dss_compliance',
            report_type='compliance',
            framework='PCI-DSS',
            frequency='weekly',
            day='monday',
            time=time(9, 0),  # 9:00 AM Monday
            recipients=['compliance@example.com'],
            format='html',
            include_evidence=True
        )
        scheduler.add_report(weekly_report)
        logger.info("  ✓ Weekly compliance report scheduled for Monday 09:00")
        
        # Schedule monthly threat intel briefing
        logger.info("Configuring monthly threat intelligence briefing...")
        monthly_report = ReportConfig(
            name='monthly_threat_intel',
            report_type='threat_intelligence',
            frequency='monthly',
            day=1,  # First day of month
            time=time(10, 0),
            recipients=['security-team@example.com'],
            format='pdf',
            include_iocs=True,
            include_trends=True
        )
        scheduler.add_report(monthly_report)
        logger.info("  ✓ Monthly threat intel report scheduled for 1st of month at 10:00")
        print()
        
        # Start the scheduler
        logger.info("Starting report scheduler...")
        await scheduler.start()
        
        logger.info("✓ Report scheduler is now running!")
        print()
        logger.info("Scheduled reports:")
        for report in scheduler.get_scheduled_reports():
            logger.info(f"  - {report.name}: {report.frequency} at {report.time}")
        print()
        logger.info("Press Ctrl+C to stop...")
        logger.info("-" * 70)
        
        # For demo purposes, generate reports immediately
        logger.info("\nGenerating sample reports now (demo mode)...")
        
        for report in [daily_report, weekly_report, monthly_report]:
            logger.info(f"\nGenerating {report.name}...")
            result = await scheduler.generate_report_now(report.name)
            
            if result.success:
                logger.info(f"  ✓ Report generated successfully")
                logger.info(f"    File: {result.file_path}")
                logger.info(f"    Size: {result.file_size} bytes")
                logger.info(f"    Format: {result.format}")
            else:
                logger.error(f"  ✗ Report generation failed: {result.error}")
            
            await asyncio.sleep(2)
        
        print()
        logger.info("=" * 70)
        logger.info("Demo reports generated. Scheduler continues running...")
        logger.info("=" * 70)
        
        # Keep running
        while True:
            await asyncio.sleep(60)
            
    except KeyboardInterrupt:
        logger.info("\n\nShutting down scheduler...")
        await scheduler.stop()
        logger.info("✓ Stopped")
    except Exception as e:
        logger.error(f"Error: {e}", exc_info=True)
        return 1
    
    return 0


if __name__ == "__main__":
    exit_code = asyncio.run(main())
    sys.exit(exit_code)
